### PR TITLE
Jf review

### PR DESCRIPTION
**Pull request by fogg-uw**
finished small changes discussed on 2022-08-10.

### CODE REVIEW

**Comment by cecileane** [comment]
Great changes @fogg-uw , and thanks for catching up the bug with the array of names.

**Comment by cecileane** [comment]
Before you squash & merge, could you possibly add your name in the [authors field](https://pkgdocs.julialang.org/v1/toml-files/#The-authors-field) in `Project.toml`?

**Comment by cecileane** [comment]
Also, do we want this first version to be `1.0.0`? Right now, it's `0.1.0` (defined in `Project.toml`). After we register this package in Julia's General registry, I'll want to use it as a dependency for other packages  right away, so in that sense, it would make sense to call this first version `1.0.0`, unless we foresee the need to quickly do breaking changes.

**Comment by fogg-uw** [comment]
> Before you squash & merge, could you possibly add your name in the [authors field](https://pkgdocs.julialang.org/v1/toml-files/#The-authors-field) in `Project.toml`?

OK.  What e-mail addresses do we want to use?  (Yours is a "noreply": is that on purpose?).

**Comment by fogg-uw** [comment]
> Also, do we want this first version to be `1.0.0`? Right now, it's `0.1.0` (defined in `Project.toml`). After we register this package in Julia's General registry, I'll want to use it as a dependency for other packages right away, so in that sense, it would make sense to call this first version `1.0.0`, unless we foresee the need to quickly do breaking changes (or rather, [incompatible API changes](https://semver.org)).

I don't see why not!

**Comment by cecileane** [comment]
Yes, the "noreply" email address is a good one to use: it's the [default github email for pushing commits](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address), to avoid exposing your private addresses.

**Comment by fogg-uw** [comment]
i'd like to ask you about code coverage tomorrow and then i should be ready to squash and merge.

**Comment by cecileane** [comment]
It might be best to stick to v0.1.0 for now, because I have ideas that may bring breaking API changes possibly. (not to work on now, but for future improvements).

**Pull request merged**
